### ISSUE TITLE
unsubscribe do not working

### ISSUE THREAD

**Issue by unclexiao** [nayarsystems/pubsub-dart#1]
I noticed that this library only provides `subscribe` and `publish` methods.

However, in actual projects, it is necessary to remove listener. Otherwise, many events will trigger many times.

So I tried to unsubscribe in my `dispose` lifecycle like this: 
```dart
  @override
  void dispose() {
    Subscriber(<String>['some_topic']).unsubscribeAll();
    super.dispose();
  }
```

But it doesn't work ...  And I found your `unsubscribe`  is **illogical**：
```dart
 bool unsubscribe(String topic) {
    var ret = false;
    if (_subscriptions.containsKey(topic)) {
      ret = _subscriptions[topic].remove(this);
      if (_subscriptions[topic].isEmpty) { // Should be remove
        _subscriptions.remove(topic);
      }
      _localSubs.remove(topic);
    }
    return ret;
  }
```

Can you fix it ?  Thank you very much!

**Comment by soyangel** [comment]
Hi,

I think there is a misunderstanding about how this library works. I will try to explain:

With the line:

```dart
Subscriber(<String>['some_topic']).unsubscribeAll();
```
you are creating a subscriber for "some topic" and then unsubscribing from it. But please note that this unsubscription only affects the Subscriber object you have just created on the same line, so nothing happens.

The correct way to use subscribers is to create one and keep the reference to it so you can unsubscribe later on onDispose.

So create it on some start method (initState maybe) assigning it to a field of the object:
```dart
this.sub = subscribe(['some topic']);
this.sub.stream.listen((msg){
   // do something here
});
```
And on onDispose:
```dart
@override
void dispose() {
  this.sub.unsubscribeAll();
  super.dispose();
}
```

Also if it you want to create some widgets using a subscriber you can make this simpler just creating the subscriber and using it directly on a StreamBuilder, like this:
```dart
StreamBuilder(
        stream: subscribe(["app.users.list"]).streamData,
        builder: (context, snapshot) {
           // Do something with snapshot.data here
          },
);
```

Hope this helps!

**Comment by unclexiao** [comment]
Okey, I suddenly understood.   It just like `Controller` ,  developer should keep the instance and call `dispose` when the widget remove from the tree. 

Thanks a lot  for your explanation.

By the way , it would be better if you could update the **README** documentation.
